-- 1-- YORUM SATIRI YAPMA : 2 ADET -- İFADESİ KULLLANILIR

---2-- DATA BASE OLUŞTURMA -DDL

--DATA BASE OLUŞTURULDU
CREATE DATABASE FARUK;

--3-DATA BASE SİLME --DDL
DROP DATABASE FARUK;

--4-- tablo oluşturma
CREATE TABLE FARUK(
	id char (4),
	NAME VARCHAR(50),
	grade REAL,--REAL ONDALIKLI SAYI İFADE ETMEKTEDİR.
	REGİSTER_DATE DATE
);

--5 VAR OLAN BİR TABLODAN YENİ BİR TABLO YARATMA
CREATE TABLE GRADES AS SELECT NAME, GRADE FROM FARUK;

--6-TABLONUN İÇİRİSİNE VERİ EKLEME
INSERT INTO FARUK VALUES (	'1001',	'ALİ',	92.8,	'2021-01-01',
INSERT INTO FARUK VALUES (	'1001',	'veli',	91.8,	'2021-01-02',
INSERT INTO FARUK VALUES (	'1001',	'deli',	93.8,	'2021-01-01'						  
);						  
--7--BAZI SUTUNLARA DATA EKLEME
INSERT INTO FARUK (NAME, GRADES) VALUES ('ASLI', 84.6);
						  
--8--TABLO TÜM VERİLERİ GETİRME
SELECT * FROM FARUK;

--9--TABLODAN BATI DATALARI GETİRME
SELECT NAME, GRADES FROM FARUK;
SELECT id, register_date FROM FARUK;